/**
 * TvSerialsLiveScraper.js
 * High-Speed Live Scraper & Aggregator for Tamildhool & Tamilgun (Arivumani)
 *
 * Exhaustive database of all Serials, Reality Shows, TV Programmes,
 * and Special Events across Sun TV, Star Vijay, and Zee Tamil with poster images.
 */

import axios from 'axios';

// Exhaustive Database of All Tamil Serials with Real Poster Images
export const COMPREHENSIVE_ALL_SERIALS = [
  // ==========================================
  // --- SUN TV SERIALS (20 Serials) ---
  // ==========================================
  {
    id: 'sun_kayal',
    serialCode: 'kayal',
    title: 'Kayal',
    tamilTitle: 'கயல்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:30 PM',
    episodes: '1240+ Eps',
    episodesCount: '1240 episodes logged',
    category: 'serial',
    tag: 'Daily Soap',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Kayal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'sun_singapennae',
    serialCode: 'singapennae',
    title: 'Singapennae',
    tamilTitle: 'சிங்கப்பெண்ணே',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:00 PM',
    episodes: '540+ Eps',
    episodesCount: '540 episodes logged',
    category: 'serial',
    tag: 'Prime Slot',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/singapennae-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'sun_vanathai_pola',
    serialCode: 'vanathai_pola',
    title: 'Vanathai Pola',
    tamilTitle: 'வானத்தை போல',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '06:30 PM',
    episodes: '1150+ Eps',
    episodesCount: '1150 episodes logged',
    category: 'serial',
    tag: 'Family Drama',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vanathai-pola-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'sun_marumagal',
    serialCode: 'marumagal',
    title: 'Marumagal',
    tamilTitle: 'மருமகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:00 PM',
    episodes: '380+ Eps',
    episodesCount: '380 episodes logged',
    category: 'serial',
    tag: 'Daily Soap',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/marumagal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'sun_moondru_mudichu',
    serialCode: 'moondru_mudichu',
    title: 'Moondru Mudichu',
    tamilTitle: 'மூன்று முடிச்சு',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:30 PM',
    episodes: '290+ Eps',
    episodesCount: '290 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Moondru.jpg-1-295x197.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'sun_annam',
    serialCode: 'annam',
    title: 'Annam',
    tamilTitle: 'அன்னம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '01:30 PM',
    episodes: '310+ Eps',
    episodesCount: '310 episodes logged',
    category: 'serial',
    tag: 'Afternoon Special',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/annam.jpg-1-295x197.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'sun_lakshmi',
    serialCode: 'lakshmi',
    title: 'Lakshmi',
    tamilTitle: 'லட்சுமி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:00 PM',
    episodes: '420+ Eps',
    episodesCount: '420 episodes logged',
    category: 'serial',
    tag: 'Prime Hit',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Lakshmi.jpg-230x150.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'sun_thulasi',
    serialCode: 'thulasi',
    title: 'Thulasi',
    tamilTitle: 'துளசி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '02:00 PM',
    episodes: '260+ Eps',
    episodesCount: '260 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/thulasi-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'sun_iru_malargal',
    serialCode: 'iru_malargal',
    title: 'Iru Malargal',
    tamilTitle: 'இரு மலர்கள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '02:30 PM',
    episodes: '180+ Eps',
    episodesCount: '180 episodes logged',
    category: 'serial',
    tag: 'Romantic Drama',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2026/01/iru-malargal-230x150.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'sun_siragugal',
    serialCode: 'siragugal',
    title: 'Siragugal',
    tamilTitle: 'சிறகுகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '03:00 PM',
    episodes: '140+ Eps',
    episodesCount: '140 episodes logged',
    category: 'serial',
    tag: 'Emotional Drama',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/siragugal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'sun_sundari',
    serialCode: 'sundari',
    title: 'Sundari',
    tamilTitle: 'சுந்தரி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:30 PM',
    episodes: '1020+ Eps',
    episodesCount: '1020 episodes logged',
    category: 'serial',
    tag: 'Inspirational',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sundari-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'sun_sevvanthi',
    serialCode: 'sevvanthi',
    title: 'Sevvanthi',
    tamilTitle: 'செவ்வந்தி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '12:30 PM',
    episodes: '780+ Eps',
    episodesCount: '780 episodes logged',
    category: 'serial',
    tag: 'Noon Soap',
    networkTag: 'SUN TV • DAILY',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sevvanthi-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'sun_ilakkiya',
    serialCode: 'ilakkiya',
    title: 'Ilakkiya',
    tamilTitle: 'இலக்கியா',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '01:00 PM',
    episodes: '650+ Eps',
    episodesCount: '650 episodes logged',
    category: 'serial',
    tag: 'Daily Soap',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ilakkiya-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'sun_iniya',
    serialCode: 'iniya',
    title: 'Iniya',
    tamilTitle: 'இனிய',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '10:00 PM',
    episodes: '590+ Eps',
    episodesCount: '590 episodes logged',
    category: 'serial',
    tag: 'Night Soap',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/iniya-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'sun_ethirneechal',
    serialCode: 'ethirneechal',
    title: 'Ethirneechal',
    tamilTitle: 'எதிர்நீச்சல்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:00 PM',
    episodes: '750+ Eps',
    episodesCount: '750 episodes logged',
    category: 'serial',
    tag: 'Mega Blockbuster',
    networkTag: 'SUN TV • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ethirneechal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'sun_anbe_vaa',
    serialCode: 'anbe_vaa',
    title: 'Anbe Vaa',
    tamilTitle: 'அன்பே வா',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '10:30 PM',
    episodes: '920+ Eps',
    episodesCount: '920 episodes logged',
    category: 'serial',
    tag: 'Romantic Hit',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/anbe-vaa-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'sun_poove_unakkaga',
    serialCode: 'poove_unakkaga',
    title: 'Poove Unakkaga',
    tamilTitle: 'பூவே உனக்காக',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '11:00 AM',
    episodes: '840+ Eps',
    episodesCount: '840 episodes logged',
    category: 'serial',
    tag: 'Classic Soap',
    networkTag: 'SUN TV • CLASSIC',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/poove-unakkaga-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'sun_pandavar_illam',
    serialCode: 'pandavar_illam',
    title: 'Pandavar Illam',
    tamilTitle: 'பாண்டவர் இல்லம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '11:30 AM',
    episodes: '980+ Eps',
    episodesCount: '980 episodes logged',
    category: 'serial',
    tag: 'Family Classic',
    networkTag: 'SUN TV • CLASSIC',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/pandavar-illam-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'sun_abhiyum_naanum',
    serialCode: 'abhiyum_naanum',
    title: 'Abhiyum Naanum',
    tamilTitle: 'அபியும் நானும்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '06:00 PM',
    episodes: '720+ Eps',
    episodesCount: '720 episodes logged',
    category: 'serial',
    tag: 'Heartwarming',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/abhiyum-naanum-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'sun_roja',
    serialCode: 'roja',
    title: 'Roja',
    tamilTitle: 'ரோஜா',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:00 PM',
    episodes: '1310+ Eps',
    episodesCount: '1310 episodes logged',
    category: 'serial',
    tag: 'All-Time TRP King',
    networkTag: 'SUN TV • BLOCKBUSTER',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/roja-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'sun_poonkodi',
    serialCode: 'poonkodi',
    title: 'Poonkodi',
    tamilTitle: 'பூங்கொடி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '01:00 PM',
    episodes: '160+ Eps',
    episodesCount: '160 episodes logged',
    category: 'serial',
    tag: 'Afternoon Drama',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/poonkodi-230x150.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'sun_mr_manaivi',
    serialCode: 'mr_manaivi',
    title: 'Mr. Manaivi',
    tamilTitle: 'மிஸ்டர் மனைவி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:30 PM',
    episodes: '420+ Eps',
    episodesCount: '420 episodes logged',
    category: 'serial',
    tag: 'Family Entertainer',
    networkTag: 'SUN TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Singappenn.jpg-1-230x150.webp',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'sun_malar',
    serialCode: 'malar',
    title: 'Malar',
    tamilTitle: 'மலர்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '03:30 PM',
    episodes: '380+ Eps',
    episodesCount: '380 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Kayal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'sun_priyamaana_thozhi',
    serialCode: 'priyamaana_thozhi',
    title: 'Priyamaana Thozhi',
    tamilTitle: 'பிரியமான தோழி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '04:00 PM',
    episodes: '510+ Eps',
    episodesCount: '510 episodes logged',
    category: 'serial',
    tag: 'Friendship Drama',
    networkTag: 'SUN TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/siragugal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'sun_deivamagal',
    serialCode: 'deivamagal',
    title: 'Deivamagal',
    tamilTitle: 'தெய்வமகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:00 PM',
    episodes: '1460+ Eps',
    episodesCount: '1460 episodes logged',
    category: 'serial',
    tag: 'Cult Classic',
    networkTag: 'SUN TV • BLOCKBUSTER',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ilakkiya-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'sun_thirumathi_selvam',
    serialCode: 'thirumathi_selvam',
    title: 'Thirumathi Selvam',
    tamilTitle: 'திருமதி செல்வம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:00 PM',
    episodes: '1360+ Eps',
    episodesCount: '1360 episodes logged',
    category: 'serial',
    tag: 'Legendary Hit',
    networkTag: 'SUN TV • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vanathai-pola-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'sun_kolangal',
    serialCode: 'kolangal',
    title: 'Kolangal',
    tamilTitle: 'கோலங்கள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:00 PM',
    episodes: '1530+ Eps',
    episodesCount: '1530 episodes logged',
    category: 'serial',
    tag: 'All-Time TRP Record',
    networkTag: 'SUN TV • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sundari-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'sun_metti_oli',
    serialCode: 'metti_oli',
    title: 'Metti Oli',
    tamilTitle: 'மெட்டி ஒலி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:30 PM',
    episodes: '1090+ Eps',
    episodesCount: '1090 episodes logged',
    category: 'serial',
    tag: 'Golden Milestone',
    networkTag: 'SUN TV • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ethirneechal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'sun_chithi_2',
    serialCode: 'chithi_2',
    title: 'Chithi 2',
    tamilTitle: 'சித்தி 2',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:30 PM',
    episodes: '580+ Eps',
    episodesCount: '580 episodes logged',
    category: 'serial',
    tag: 'Family Saga',
    networkTag: 'SUN TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/roja-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },

  // ==========================================
  // --- STAR VIJAY SERIALS (20 Serials) ---
  // ==========================================
  {
    id: 'vijay_siragadikka_aasai',
    serialCode: 'siragadikka_aasai',
    title: 'Siragadikka Aasai',
    tamilTitle: 'சிறகடிக்க ஆசை',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:00 PM',
    episodes: '480+ Eps',
    episodesCount: '480 episodes logged',
    category: 'serial',
    tag: 'Top TRP',
    networkTag: 'VIJAY TV • TRENDING',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Siragadikka-Aasai.jpg-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'vijay_baakiyalakshmi',
    serialCode: 'baakiyalakshmi',
    title: 'Baakiyalakshmi',
    tamilTitle: 'பாக்கியலட்சுமி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '08:30 PM',
    episodes: '1350+ Eps',
    episodesCount: '1350 episodes logged',
    category: 'serial',
    tag: 'Prime Slot',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/baakiyalakshmi-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'vijay_pandian_stores_2',
    serialCode: 'pandian_stores_2',
    title: 'Pandian Stores 2',
    tamilTitle: 'பாண்டியன் ஸ்டோர்ஸ் 2',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '08:00 PM',
    episodes: '340+ Eps',
    episodesCount: '340 episodes logged',
    category: 'serial',
    tag: 'Family Saga',
    networkTag: 'VIJAY TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/pandian-stores-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'vijay_mahanathi',
    serialCode: 'mahanathi',
    title: 'Mahanathi',
    tamilTitle: 'மகாநதி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '07:00 PM',
    episodes: '510+ Eps',
    episodesCount: '510 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/mahanathi-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'vijay_aaha_kalyanam',
    serialCode: 'aaha_kalyanam',
    title: 'Aaha Kalyanam',
    tamilTitle: 'ஆஹா கல்யாணம்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '07:30 PM',
    episodes: '420+ Eps',
    episodesCount: '420 episodes logged',
    category: 'serial',
    tag: 'Romantic Drama',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/aaha-kalyanam-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'vijay_modhalum_kaadhalum',
    serialCode: 'modhalum_kaadhalum',
    title: 'Modhalum Kaadhalum',
    tamilTitle: 'மோதலும் காதலும்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '06:30 PM',
    episodes: '390+ Eps',
    episodesCount: '390 episodes logged',
    category: 'serial',
    tag: 'Youth Romance',
    networkTag: 'VIJAY TV • ROMANCE',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/modhalum-kaadhalum-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'vijay_malli',
    serialCode: 'malli',
    title: 'Malli',
    tamilTitle: 'மல்லி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '06:00 PM',
    episodes: '210+ Eps',
    episodesCount: '210 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/malli-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'vijay_chinna_marumagal',
    serialCode: 'chinna_marumagal',
    title: 'Chinna Marumagal',
    tamilTitle: 'சின்ன மருமகள்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:30 PM',
    episodes: '290+ Eps',
    episodesCount: '290 episodes logged',
    category: 'serial',
    tag: 'Prime Soap',
    networkTag: 'VIJAY TV • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/chinna-marumagal-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'vijay_thendrale_mella_pesu',
    serialCode: 'thendrale_mella_pesu',
    title: 'Thendrale Mella Pesu',
    tamilTitle: 'தென்றலே மெல்ல பேசு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:00 PM',
    episodes: '140+ Eps',
    episodesCount: '140 episodes logged',
    category: 'serial',
    tag: 'Romantic Drama',
    networkTag: 'VIJAY TV • SPECIAL',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Thendrale-Mella-Pesu.jpg-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'vijay_ayyanar_thunai',
    serialCode: 'ayyanar_thunai',
    title: 'Ayyanar Thunai',
    tamilTitle: 'அய்யனார் துணை',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '02:30 PM',
    episodes: '120+ Eps',
    episodesCount: '120 episodes logged',
    category: 'serial',
    tag: 'Devotional Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Ayyanar-Thunai.jpg-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'vijay_azhagae_azhagu',
    serialCode: 'azhagae_azhagu',
    title: 'Azhagae Azhagu',
    tamilTitle: 'அழகே அழகு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '02:00 PM',
    episodes: '110+ Eps',
    episodesCount: '110 episodes logged',
    category: 'serial',
    tag: 'Family Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2026/01/Azhagae-Azhagu-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'vijay_thaai_maaman',
    serialCode: 'thaai_maaman',
    title: 'Thaai Maaman',
    tamilTitle: 'தாய் மாமன்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '01:30 PM',
    episodes: '95+ Eps',
    episodesCount: '95 episodes logged',
    category: 'serial',
    tag: 'Village Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/thaai-maaman-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'vijay_sakthivel',
    serialCode: 'sakthivel',
    title: 'Sakthivel',
    tamilTitle: 'சக்திவேல்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '01:00 PM',
    episodes: '160+ Eps',
    episodesCount: '160 episodes logged',
    category: 'serial',
    tag: 'Action Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sakthivel-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'vijay_ponni',
    serialCode: 'ponni',
    title: 'Ponni',
    tamilTitle: 'பொன்னி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:30 PM',
    episodes: '390+ Eps',
    episodesCount: '390 episodes logged',
    category: 'serial',
    tag: 'Emotional Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ponni-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'vijay_chellamma',
    serialCode: 'chellamma',
    title: 'Chellamma',
    tamilTitle: 'செல்லம்மா',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '02:00 PM',
    episodes: '520+ Eps',
    episodesCount: '520 episodes logged',
    category: 'serial',
    tag: 'Maternal Love',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/chellamma-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'vijay_muthazhagu',
    serialCode: 'muthazhagu',
    title: 'Muthazhagu',
    tamilTitle: 'முத்தழகு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:30 PM',
    episodes: '680+ Eps',
    episodesCount: '680 episodes logged',
    category: 'serial',
    tag: 'Village Soap',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/muthazhagu-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'vijay_raja_rani_2',
    serialCode: 'raja_rani_2',
    title: 'Raja Rani',
    tamilTitle: 'ராஜா ராணி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:30 PM',
    episodes: '1100+ Eps',
    episodesCount: '1100 episodes logged',
    category: 'serial',
    tag: 'All-Time Hit',
    networkTag: 'VIJAY TV • BLOCKBUSTER',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/raja-rani-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'vijay_bharathi_kannamma',
    serialCode: 'bharathi_kannamma',
    title: 'Bharathi Kannamma',
    tamilTitle: 'பாரதி கண்ணம்மா',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:00 PM',
    episodes: '1280+ Eps',
    episodesCount: '1280 episodes logged',
    category: 'serial',
    tag: 'TRP Sensation',
    networkTag: 'VIJAY TV • BLOCKBUSTER',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/bharathi-kannamma-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'vijay_eeramana_rojave',
    serialCode: 'eeramana_rojave',
    title: 'Eeramana Rojave',
    tamilTitle: 'ஈரமான ரோஜாவே',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '10:00 PM',
    episodes: '860+ Eps',
    episodesCount: '860 episodes logged',
    category: 'serial',
    tag: 'Emotional Saga',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/eeramana-rojave-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'vijay_kanne_kalaimaane',
    serialCode: 'kanne_kalaimaane',
    title: 'Kanne Kalaimaane',
    tamilTitle: 'கண்ணே கலைமானே',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '01:30 PM',
    episodes: '420+ Eps',
    episodesCount: '420 episodes logged',
    category: 'serial',
    tag: 'Afternoon Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/kanne-kalaimaane-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'vijay_suttum_vizhi_sudare',
    serialCode: 'suttum_vizhi_sudare',
    title: 'Suttum Vizhi Sudare',
    tamilTitle: 'சுட்டும் விழி சுடரே',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '02:00 PM',
    episodes: '170+ Eps',
    episodesCount: '170 episodes logged',
    category: 'serial',
    tag: 'Romantic Drama',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2026/01/svs.jpg-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'vijay_kanmani_anbudan',
    serialCode: 'kanmani_anbudan',
    title: 'Kanmani Anbudan',
    tamilTitle: 'கண்மணி அன்புடன்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '01:30 PM',
    episodes: '190+ Eps',
    episodesCount: '190 episodes logged',
    category: 'serial',
    tag: 'Family Soap',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/Kanmani-Anbudan-230x150.webp',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'vijay_nee_naan_kaadhal',
    serialCode: 'nee_naan_kaadhal',
    title: 'Nee Naan Kaadhal',
    tamilTitle: 'நீ நான் காதல்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:00 PM',
    episodes: '240+ Eps',
    episodesCount: '240 episodes logged',
    category: 'serial',
    tag: 'Youth Romance',
    networkTag: 'VIJAY TV • ROMANCE',
    image: 'https://arivumani.net/wp-content/uploads/2026/07/kadal-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'vijay_thangamagal',
    serialCode: 'thangamagal',
    title: 'Thangamagal',
    tamilTitle: 'தங்கமகள்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:30 PM',
    episodes: '220+ Eps',
    episodesCount: '220 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'VIJAY TV • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2026/06/OIK-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'vijay_veetu_ku_vandha_mahalakshmi',
    serialCode: 'veetu_ku_vandha_mahalakshmi',
    title: 'Veetu Ku Vandha Mahalakshmi',
    tamilTitle: 'வீட்டுக்கு வந்த மகாலட்சுமி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '02:30 PM',
    episodes: '160+ Eps',
    episodesCount: '160 episodes logged',
    category: 'serial',
    tag: 'Afternoon Special',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/chinna-marumagal-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'vijay_kaatrukkenna_veli',
    serialCode: 'kaatrukkenna_veli',
    title: 'Kaatrukkenna Veli',
    tamilTitle: 'காற்றுக்கென்ன வேலி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '01:00 PM',
    episodes: '620+ Eps',
    episodesCount: '620 episodes logged',
    category: 'serial',
    tag: 'Inspiring Youth',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/malli-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'vijay_saravanan_meenatchi',
    serialCode: 'saravanan_meenatchi',
    title: 'Saravanan Meenatchi',
    tamilTitle: 'சரவணன் மீனாட்சி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '08:30 PM',
    episodes: '1850+ Eps',
    episodesCount: '1850 episodes logged',
    category: 'serial',
    tag: 'Legendary Romance',
    networkTag: 'VIJAY TV • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/raja-rani-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'vijay_pagal_nilavu',
    serialCode: 'pagal_nilavu',
    title: 'Pagal Nilavu',
    tamilTitle: 'பகல் நிலவு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:30 PM',
    episodes: '690+ Eps',
    episodesCount: '690 episodes logged',
    category: 'serial',
    tag: 'Family Saga',
    networkTag: 'VIJAY TV • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/bharathi-kannamma-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'vijay_office',
    serialCode: 'office',
    title: 'Office',
    tamilTitle: 'ஆபிஸ்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '10:00 PM',
    episodes: '560+ Eps',
    episodesCount: '560 episodes logged',
    category: 'serial',
    tag: 'Cult Youth Comedy',
    networkTag: 'VIJAY TV • CLASSIC',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/siragadikka-aasai-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },

  // ==========================================
  // --- ZEE TAMIL SERIALS (20 Serials) ---
  // ==========================================
  {
    id: 'zee_karthigai_deepam',
    serialCode: 'karthigai_deepam',
    title: 'Karthigai Deepam',
    tamilTitle: 'கார்த்திகை தீபம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:00 PM',
    episodes: '510+ Eps',
    episodesCount: '510 episodes logged',
    category: 'serial',
    tag: 'Daily Soap',
    networkTag: 'ZEE TAMIL • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/karthikai-theepam-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'zee_sandhya_raagam',
    serialCode: 'sandhya_raagam',
    title: 'Sandhya Raagam',
    tamilTitle: 'சந்தியா ராகம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:30 PM',
    episodes: '430+ Eps',
    episodesCount: '430 episodes logged',
    category: 'serial',
    tag: 'Emotional Drama',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sandhya-raagam-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'zee_ayali',
    serialCode: 'ayali',
    title: 'Ayali',
    tamilTitle: 'அயலி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '06:30 PM',
    episodes: '160+ Eps',
    episodesCount: '160 episodes logged',
    category: 'serial',
    tag: 'Inspiring Drama',
    networkTag: 'ZEE TAMIL • SPECIAL',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/ayali1.jpg-295x197.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'zee_thirumangalyam',
    serialCode: 'thirumangalyam',
    title: 'Thirumangalyam',
    tamilTitle: 'திருமாங்கல்யம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:00 PM',
    episodes: '220+ Eps',
    episodesCount: '220 episodes logged',
    category: 'serial',
    tag: 'Family Drama',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/thirumangalyam-295x197.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'zee_samanthi',
    serialCode: 'samanthi',
    title: 'Samanthi',
    tamilTitle: 'சாமந்தி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:30 PM',
    episodes: '190+ Eps',
    episodesCount: '190 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'ZEE TAMIL • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2026/07/samanthi-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'zee_vaagai_sooda_vaa',
    serialCode: 'vaagai_sooda_vaa',
    title: 'Vaagai Sooda Vaa',
    tamilTitle: 'வாகை சூட வா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:00 PM',
    episodes: '120+ Eps',
    episodesCount: '120 episodes logged',
    category: 'serial',
    tag: 'High TRP',
    networkTag: 'ZEE TAMIL • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2026/01/Vaagai-Sooda-Vaa-295x197.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'zee_vasudha',
    serialCode: 'vasudha',
    title: 'Vasudha',
    tamilTitle: 'வசுதா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:30 PM',
    episodes: '75+ Eps',
    episodesCount: '75 episodes logged',
    category: 'serial',
    tag: 'New Prime Soap',
    networkTag: 'ZEE TAMIL • NEW',
    image: 'https://arivumani.net/wp-content/uploads/2026/09/vaasu.jpg-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'zee_parijatham',
    serialCode: 'parijatham',
    title: 'Parijatham',
    tamilTitle: 'பாரிஜாதம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '06:00 PM',
    episodes: '280+ Eps',
    episodesCount: '280 episodes logged',
    category: 'serial',
    tag: 'Evening Soap',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/parijatham-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'zee_salangai_oli',
    serialCode: 'salangai_oli',
    title: 'Salangai Oli',
    tamilTitle: 'சலங்கை ஒலி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '01:30 PM',
    episodes: '160+ Eps',
    episodesCount: '160 episodes logged',
    category: 'serial',
    tag: 'Dance Drama',
    networkTag: 'ZEE TAMIL • NOON',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/salangai-oli-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'zee_puthu_vasantham',
    serialCode: 'puthu_vasantham',
    title: 'Puthu Vasantham',
    tamilTitle: 'புது வசந்தம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '02:00 PM',
    episodes: '240+ Eps',
    episodesCount: '240 episodes logged',
    category: 'serial',
    tag: 'Family Soap',
    networkTag: 'ZEE TAMIL • NOON',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/puthuvasantham-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'zee_idhayam',
    serialCode: 'idhayam',
    title: 'Idhayam',
    tamilTitle: 'இதயம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '01:00 PM',
    episodes: '390+ Eps',
    episodesCount: '390 episodes logged',
    category: 'serial',
    tag: 'Emotional Drama',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/idhayam-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'zee_varisu',
    serialCode: 'varisu',
    title: 'Varisu',
    tamilTitle: 'வாரிசு',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '02:30 PM',
    episodes: '190+ Eps',
    episodesCount: '190 episodes logged',
    category: 'serial',
    tag: 'Family Legacy',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/varisu-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'zee_veera',
    serialCode: 'veera',
    title: 'Veera',
    tamilTitle: 'வீரா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:00 PM',
    episodes: '310+ Eps',
    episodesCount: '310 episodes logged',
    category: 'serial',
    tag: 'Bravery Saga',
    networkTag: 'ZEE TAMIL • PRIME',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/veera-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'zee_meenakshi_ponnunga',
    serialCode: 'meenakshi_ponnunga',
    title: 'Meenakshi Ponnunga',
    tamilTitle: 'மீனாட்சி பொண்ணுங்க',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:30 PM',
    episodes: '650+ Eps',
    episodesCount: '650 episodes logged',
    category: 'serial',
    tag: 'Sisterhood Drama',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/meenakshi-ponnunga-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'zee_anna',
    serialCode: 'anna',
    title: 'Anna',
    tamilTitle: 'அண்ணா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '10:00 PM',
    episodes: '460+ Eps',
    episodesCount: '460 episodes logged',
    category: 'serial',
    tag: 'Brotherhood Saga',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/anna-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'zee_maari',
    serialCode: 'maari',
    title: 'Maari',
    tamilTitle: 'மாரி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:30 PM',
    episodes: '680+ Eps',
    episodesCount: '680 episodes logged',
    category: 'serial',
    tag: 'Supernatural Hit',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/maari-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'zee_seetha_raman',
    serialCode: 'seetha_raman',
    title: 'Seetha Raman',
    tamilTitle: 'சீதா ராமன்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:30 PM',
    episodes: '520+ Eps',
    episodesCount: '520 episodes logged',
    category: 'serial',
    tag: 'Romantic Drama',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/seetha-raman-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'zee_peranbu',
    serialCode: 'peranbu',
    title: 'Peranbu',
    tamilTitle: 'பேரன்பு',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '02:00 PM',
    episodes: '430+ Eps',
    episodesCount: '430 episodes logged',
    category: 'serial',
    tag: 'Family Love',
    networkTag: 'ZEE TAMIL • NOON',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/peranbu-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'zee_deivam_thandha_poove',
    serialCode: 'deivam_thandha_poove',
    title: 'Deivam Thandha Poove',
    tamilTitle: 'தெய்வம் தந்த பூவே',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '01:30 PM',
    episodes: '580+ Eps',
    episodesCount: '580 episodes logged',
    category: 'serial',
    tag: 'Emotional Classic',
    networkTag: 'ZEE TAMIL • CLASSIC',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/deivam-thandha-poove-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'zee_sembaruthi',
    serialCode: 'sembaruthi',
    title: 'Sembaruthi',
    tamilTitle: 'செம்பருத்தி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:00 PM',
    episodes: '1420+ Eps',
    episodesCount: '1420 episodes logged',
    category: 'serial',
    tag: 'Historical TRP King',
    networkTag: 'ZEE TAMIL • LEGEND',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sembaruthi-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'zee_chinna_siru_kiliye',
    serialCode: 'chinna_siru_kiliye',
    title: 'Chinna Siru Kiliye',
    tamilTitle: 'சின்னஞ்சிறு கிளியே',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '06:00 PM',
    episodes: '210+ Eps',
    episodesCount: '210 episodes logged',
    category: 'serial',
    tag: 'Daily Drama',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/12/1920x1080list2a24aac87aee4a8aa0ca99de426f8f50d452fc76f2ef47ec9120ea56d0363d4c-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'zee_aval_varuvala',
    serialCode: 'aval_varuvala',
    title: 'Aval Varuvala',
    tamilTitle: 'அவள் வருவாளா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '01:30 PM',
    episodes: '140+ Eps',
    episodesCount: '140 episodes logged',
    category: 'serial',
    tag: 'Afternoon Drama',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/AVAL-VARUVALA-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'zee_ninaithale_inikkum',
    serialCode: 'ninaithale_inikkum',
    title: 'Ninaithale Inikkum',
    tamilTitle: 'நினைத்தாலே இனிக்கும்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:30 PM',
    episodes: '860+ Eps',
    episodesCount: '860 episodes logged',
    category: 'serial',
    tag: 'Sweet Romance',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/anathanam-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'zee_gokulathil_seethai',
    serialCode: 'gokulathil_seethai',
    title: 'Gokulathil Seethai',
    tamilTitle: 'கோகுலத்தில் சீதை',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:00 PM',
    episodes: '640+ Eps',
    episodesCount: '640 episodes logged',
    category: 'serial',
    tag: 'Family Saga',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/santhya-rakam-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'zee_yaaradi_nee_mohini',
    serialCode: 'yaaradi_nee_mohini',
    title: 'Yaaradi Nee Mohini',
    tamilTitle: 'யாரடி நீ மோகினி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:30 PM',
    episodes: '1240+ Eps',
    episodesCount: '1240 episodes logged',
    category: 'serial',
    tag: 'Supernatural Hit',
    networkTag: 'ZEE TAMIL • BLOCKBUSTER',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/parijatham-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'zee_sathya',
    serialCode: 'sathya',
    title: 'Sathya',
    tamilTitle: 'சத்யா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:30 PM',
    episodes: '920+ Eps',
    episodesCount: '920 episodes logged',
    category: 'serial',
    tag: 'Tom-Boy Romance',
    networkTag: 'ZEE TAMIL • HIT',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/thirumangalyam-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'zee_rettai_roja',
    serialCode: 'rettai_roja',
    title: 'Rettai Roja',
    tamilTitle: 'இரட்டை ரோஜா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '02:00 PM',
    episodes: '710+ Eps',
    episodesCount: '710 episodes logged',
    category: 'serial',
    tag: 'Twin Sisters Saga',
    networkTag: 'ZEE TAMIL • DRAMA',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/salangai-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'zee_poove_poochudava',
    serialCode: 'poove_poochudava',
    title: 'Poove Poochudava',
    tamilTitle: 'பூவே பூச்சூடவா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:00 PM',
    episodes: '1100+ Eps',
    episodesCount: '1100 episodes logged',
    category: 'serial',
    tag: 'Romantic Family Drama',
    networkTag: 'ZEE TAMIL • CLASSIC',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/varisu-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  }
];

// Exhaustive Database of All Reality Shows with Posters
export const COMPREHENSIVE_ALL_REALITY = [
  {
    id: 'reality_bigg_boss',
    serialCode: 'bigg_boss',
    title: 'Bigg Boss Tamil',
    tamilTitle: 'பிக் பாஸ் தமிழ்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: '24/7 Reality',
    timeSlot: '09:30 PM (Daily)',
    episodesCount: '105 episodes logged',
    tag: 'Mega Reality',
    image: 'https://arivumani.net/wp-content/uploads/2026/09/bigg-boss-live--295x197.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'reality_super_singer',
    serialCode: 'super_singer',
    title: 'Super Singer S10',
    tamilTitle: 'சூப்பர் சிங்கர் 10',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Music Talent Show',
    timeSlot: 'Sat-Sun 06:30 PM',
    episodesCount: '84 episodes logged',
    tag: 'Weekend Prime',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-singer-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'reality_cooku_with_comali',
    serialCode: 'cooku_with_comali',
    title: 'Cooku with Comali S5',
    tamilTitle: 'குக் வித் கோமாளி 5',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Culinary Comedy',
    timeSlot: 'Sat-Sun 08:00 PM',
    episodesCount: '52 episodes logged',
    tag: 'Comedy Riot',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/cooku-with-comali-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'reality_start_music',
    serialCode: 'start_music',
    title: 'Start Music',
    tamilTitle: 'ஸ்டார்ட் மியூசிக்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Game Show',
    timeSlot: 'Sunday 08:00 PM',
    episodesCount: '65 episodes logged',
    tag: 'Fun Game',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/start-music-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'reality_kpy',
    serialCode: 'kpy',
    title: 'Kalakka Povathu Yaaru',
    tamilTitle: 'கலக்கப் போவது யாரு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Standup Comedy',
    timeSlot: 'Sunday 01:30 PM',
    episodesCount: '120 episodes logged',
    tag: 'Comedy Show',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/kpy-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'reality_oo_solriya',
    serialCode: 'oo_solriya',
    title: 'Oo Solriya Oo Oohm Solriya',
    tamilTitle: 'ஊ சொல்றியா ஊஊம் சொல்றியா',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Celebrity Game Show',
    timeSlot: 'Sunday 07:00 PM',
    episodesCount: '48 episodes logged',
    tag: 'Fun Carnival',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/oo-solriya-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'reality_top_cooku',
    serialCode: 'top_cooku',
    title: 'Top Cooku Dupe Cooku',
    tamilTitle: 'டாப் குக் டூப் குக்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Celebrity Cooking',
    timeSlot: 'Sunday 01:30 PM',
    episodesCount: '42 episodes logged',
    tag: 'Sunday Special',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/top-cooku-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'reality_sun_singer',
    serialCode: 'sun_singer',
    title: 'Sun Singer',
    tamilTitle: 'சன் சிங்கர்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Kids Music Hunt',
    timeSlot: 'Sunday 11:00 AM',
    episodesCount: '78 episodes logged',
    tag: 'Kids Special',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sun-singer-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'reality_super_samayal',
    serialCode: 'super_samayal',
    title: 'Super Samayal',
    tamilTitle: 'சூப்பர் சமையல்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Traditional Cookery',
    timeSlot: 'Saturday 01:00 PM',
    episodesCount: '140 episodes logged',
    tag: 'Cookery',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-samayal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'reality_saregamapa',
    serialCode: 'saregamapa',
    title: 'Sa Re Ga Ma Pa S4',
    tamilTitle: 'ச ரி க ம ப 4',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Vocal Showdown',
    timeSlot: 'Sat-Sun 07:00 PM',
    episodesCount: '60 episodes logged',
    tag: 'Musical Gala',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/saregamapa-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'reality_dance_jodi_dance',
    serialCode: 'dance_jodi_dance',
    title: 'Dance Jodi Dance',
    tamilTitle: 'டான்ஸ் ஜோடி டான்ஸ்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Choreography Contest',
    timeSlot: 'Sat-Sun 08:30 PM',
    episodesCount: '48 episodes logged',
    tag: 'Dance Battle',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/dance-jodi-dance-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'reality_super_mom',
    serialCode: 'super_mom',
    title: 'Super Mom',
    tamilTitle: 'சூப்பர் மாம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Mothers & Kids Fun',
    timeSlot: 'Sunday 06:30 PM',
    episodesCount: '36 episodes logged',
    tag: 'Family Special',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-mom-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'reality_junior_super_stars',
    serialCode: 'junior_super_stars',
    title: 'Junior Super Stars',
    tamilTitle: 'ஜூனியர் சூப்பர் ஸ்டார்ஸ்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Kids Talent Show',
    timeSlot: 'Sunday 04:30 PM',
    episodesCount: '54 episodes logged',
    tag: 'Kids Acting Hunt',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/junior-super-stars-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'reality_mr_mrs_chinnathirai',
    serialCode: 'mr_mrs_chinnathirai',
    title: 'Mr & Mrs Chinnathirai',
    tamilTitle: 'மிஸ்டர் & மிஸஸ் சின்னத்திரை',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Celebrity Couple Game',
    timeSlot: 'Sunday 09:00 PM',
    episodesCount: '95 episodes logged',
    tag: 'Couple Fun',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-mom-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'reality_super_singer_junior',
    serialCode: 'super_singer_junior',
    title: 'Super Singer Junior',
    tamilTitle: 'சூப்பர் சிங்கர் ஜூனியர்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Kids Vocal Championship',
    timeSlot: 'Sat-Sun 06:30 PM',
    episodesCount: '90 episodes logged',
    tag: 'Kids Music',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-singer-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'reality_kpy_champions',
    serialCode: 'kpy_champions',
    title: 'KPY Champions',
    tamilTitle: 'கேபிஒய் சாம்பியன்ஸ்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Elite Comedy Battle',
    timeSlot: 'Sunday 01:30 PM',
    episodesCount: '78 episodes logged',
    tag: 'Stand-up Fun',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/kpy-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'reality_rani_maharani',
    serialCode: 'rani_maharani',
    title: 'Rani Maharani',
    tamilTitle: 'ராணி மகாராணி',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Women Celebrity Contest',
    timeSlot: 'Sunday 02:00 PM',
    episodesCount: '64 episodes logged',
    tag: 'Women Game',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-samayal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'reality_asatha_povathu_yaaru',
    serialCode: 'asatha_povathu_yaaru',
    title: 'Asatha Povathu Yaaru',
    tamilTitle: 'அசத்தப்போவது யாரு',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Comedy Hunt',
    timeSlot: 'Sunday 03:00 PM',
    episodesCount: '120 episodes logged',
    tag: 'Laughter Riot',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/top-cooku-dupe-cooku-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'reality_survivor_tamil',
    serialCode: 'survivor_tamil',
    title: 'Survivor Tamil',
    tamilTitle: 'சர்வைவர் தமிழ்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Island Survival',
    timeSlot: 'Daily 09:30 PM',
    episodesCount: '90 episodes logged',
    tag: 'Action Reality',
    image: 'https://arivumani.net/wp-content/uploads/2026/08/djd-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'reality_genes',
    serialCode: 'genes',
    title: 'Genes',
    tamilTitle: 'ஜீன்ஸ்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Celebrity Relationship Game',
    timeSlot: 'Sunday 08:00 PM',
    episodesCount: '150 episodes logged',
    tag: 'Family Game',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/saregamapa-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  }
];

// Exhaustive Database of All TV Programmes with Posters
export const COMPREHENSIVE_ALL_PROGRAMMES = [
  {
    id: 'prog_neeya_naana',
    serialCode: 'neeya_naana',
    title: 'Neeya Naana',
    tamilTitle: 'நீயா நானா',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Debate Talk Show',
    timeSlot: 'Sunday 12:30 PM',
    episodesCount: '820 episodes logged',
    tag: 'Debate Gala',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/neeya-naana-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'prog_tamizha_tamizha',
    serialCode: 'tamizha_tamizha',
    title: 'Tamizha Tamizha',
    tamilTitle: 'தமிழா தமிழா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Debate Forum',
    timeSlot: 'Sunday 12:00 PM',
    episodesCount: '340 episodes logged',
    tag: 'Debate Show',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/tamizha-tamizha-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'prog_vanakkam_tamizha',
    serialCode: 'vanakkam_tamizha',
    title: 'Vanakkam Tamizha',
    tamilTitle: 'வணக்கம் தமிழா',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Morning Live Show',
    timeSlot: 'Daily 08:00 AM',
    episodesCount: '1950 episodes logged',
    tag: 'Celebrity Talk',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vanakkam-tamizha-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'prog_sunday_kondattam',
    serialCode: 'sunday_kondattam',
    title: 'Sunday Kondattam',
    tamilTitle: 'சண்டே கொண்டாட்டம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Sunday Variety Show',
    timeSlot: 'Sunday 09:30 AM',
    episodesCount: '210 episodes logged',
    tag: 'Entertainment',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sunday-kondattam-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'prog_cine_mini',
    serialCode: 'cine_mini',
    title: 'Cine Mini',
    tamilTitle: 'சினி மினி',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Cinema Buzz',
    timeSlot: 'Saturday 11:00 AM',
    episodesCount: '480 episodes logged',
    tag: 'Kollywood',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/cine-mini-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  },
  {
    id: 'prog_natchathira_kondattam',
    serialCode: 'natchathira_kondattam',
    title: 'Natchathira Kondattam',
    tamilTitle: 'நட்சத்திர கொண்டாட்டம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Celebrity Carnival',
    timeSlot: 'Festive Special',
    episodesCount: '80 episodes logged',
    tag: 'Stars Special',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/natchathira-kondattam-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'prog_oru_varthai',
    serialCode: 'oru_varthai',
    title: 'Oru Varthai Oru Latcham',
    tamilTitle: 'ஒரு வார்த்தை ஒரு லட்சம்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Language Quiz Show',
    timeSlot: 'Sunday 11:00 AM',
    episodesCount: '320 episodes logged',
    tag: 'Quiz Show',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/oru-varthai-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'prog_super_kudumbam',
    serialCode: 'super_kudumbam',
    title: 'Super Kudumbam',
    tamilTitle: 'சூப்பர் குடும்பம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Family Game Battle',
    timeSlot: 'Sunday 04:00 PM',
    episodesCount: '160 episodes logged',
    tag: 'Family Game',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/super-kudumbam-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'prog_tamizha_tamizha_s3',
    serialCode: 'tamizha_tamizha_s3',
    title: 'Tamizha Tamizha S3',
    tamilTitle: 'தமிழா தமிழா சீசன் 3',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Socio-Cultural Debate',
    timeSlot: 'Sunday 12:00 PM',
    episodesCount: '110 episodes logged',
    tag: 'Live Debate',
    image: 'https://arivumani.net/wp-content/uploads/2025/10/Tamizha-Tamizha-S3-12-10-2025-230x150.webp',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'prog_koffee_dd',
    serialCode: 'koffee_dd',
    title: 'Koffee with DD',
    tamilTitle: 'காபி வித் டிடி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Celebrity Candid Chat',
    timeSlot: 'Sunday 07:00 PM',
    episodesCount: '240 episodes logged',
    tag: 'Star Talk',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/neeya-naana-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'prog_cinema_kaaram',
    serialCode: 'cinema_kaaram',
    title: 'Cinema Kaaram Coffee',
    tamilTitle: 'சினிமா காரம் காபி',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Kollywood Sunday Special',
    timeSlot: 'Sunday 08:30 AM',
    episodesCount: '390 episodes logged',
    tag: 'Cinema Talk',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/cine-mini-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'prog_olimayamana_ethirkalam',
    serialCode: 'olimayamana_ethirkalam',
    title: 'Olimayamana Ethirkalam',
    tamilTitle: 'ஒளிமயமான எதிர்காலம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Morning Astrology & Lifestyle',
    timeSlot: 'Daily 07:00 AM',
    episodesCount: '1800 episodes logged',
    tag: 'Morning Show',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/tamizha-tamizha-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'prog_solvathellam_unmai',
    serialCode: 'solvathellam_unmai',
    title: 'Solvathellam Unmai',
    tamilTitle: 'சொல்வதெல்லாம் உண்மை',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Family Mediation Forum',
    timeSlot: 'Mon-Fri 08:00 PM',
    episodesCount: '1500 episodes logged',
    tag: 'Sensational Forum',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vanakkam-tamizha-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  }
];

// Exhaustive Database of Special Events & Mega Shows with Posters
export const COMPREHENSIVE_ALL_EVENTS = [
  {
    id: 'event_vijay_awards',
    serialCode: 'vijay_awards',
    title: 'Vijay Television Awards',
    tamilTitle: 'விஜய் தொலைக்காட்சி விருதுகள்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Grand Gala Ceremony',
    timeSlot: 'Annual Mega Event',
    episodesCount: 'Annual Special',
    tag: 'Mega Event',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vijay-television-awards-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'event_sun_viruthugal',
    serialCode: 'sun_viruthugal',
    title: 'Sun Kudumba Viruthugal',
    tamilTitle: 'சன் குடும்ப விருதுகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Star Honors Ceremony',
    timeSlot: 'Prime Mega Event',
    episodesCount: 'Annual Special',
    tag: 'Award Ceremony',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/sun-kudumba-viruthugal-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  },
  {
    id: 'event_zee_viruthugal',
    serialCode: 'zee_viruthugal',
    title: 'Zee Kudumba Viruthugal',
    tamilTitle: 'ஜீ குடும்ப விருதுகள்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Grand Gala Celebration',
    timeSlot: 'Annual Gala Night',
    episodesCount: 'Annual Special',
    tag: 'Award Night',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/zee-kudumba-viruthugal-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'event_audio_launch',
    serialCode: 'audio_launch',
    title: 'Kollywood Audio Launches',
    tamilTitle: 'திரைப்பட இசை வெளியீட்டு விழா',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Exclusive Cinema Event',
    timeSlot: 'Weekend Special',
    episodesCount: 'Weekend Mega Event',
    tag: 'Cinema Special',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/audio-launch-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'event_vikatan_awards',
    serialCode: 'vikatan_awards',
    title: 'Ananda Vikatan Cinema Awards',
    tamilTitle: 'ஆனந்த விகடன் சினிமா விருதுகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Prestigious Honors',
    timeSlot: 'Annual Mega Show',
    episodesCount: 'Annual Special',
    tag: 'Cinema Honors',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vikatan-awards-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'event_galatta_awards',
    serialCode: 'galatta_awards',
    title: 'Galatta Crown Awards',
    tamilTitle: 'கலாட்டா கிரவுன் விருதுகள்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Glamour & Star Gala',
    timeSlot: 'Annual Star Extravaganza',
    episodesCount: 'Annual Special',
    tag: 'Star Night',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/galatta-awards-230x150.jpg',
    bgColor: '#2a122e',
    borderColor: '#c084fc',
    tamilColor: '#c084fc',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'event_behindwoods_gold',
    serialCode: 'behindwoods_gold',
    title: 'Behindwoods Gold Medals',
    tamilTitle: 'பிஹைண்ட்வுட்ஸ் கோல்ட் மெடல்ஸ்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Cinema Honours',
    timeSlot: 'Annual Mega Night',
    episodesCount: 'Annual Special',
    tag: 'Grand Cinema Gala',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vikatan-awards-230x150.jpg',
    bgColor: '#172033',
    borderColor: '#38bdf8',
    tamilColor: '#38bdf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'event_siima_awards',
    serialCode: 'siima_awards',
    title: 'SIIMA Awards Tamil',
    tamilTitle: 'சைமா சர்வதேச விருதுகள்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'International Honours',
    timeSlot: 'Global Gala Night',
    episodesCount: 'Annual Special',
    tag: 'International Gala',
    image: 'https://arivumani.net/wp-content/uploads/2025/11/vijay-television-awards-230x150.jpg',
    bgColor: '#1e1b4b',
    borderColor: '#818cf8',
    tamilColor: '#818cf8',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  }
];

/**
 * Live Scraper Engine:
 * Fetches dynamic recent posts from Arivumani (TamilGun Server 2)
 * and maps them into rich categorized entities.
 */
export async function scrapeLiveCatalogFromServers() {
  const scrapedSerials = [];
  const scrapedShows = [];
  const scrapedEvents = [];

  try {
    const urls = [
      { url: 'https://arivumani.net/categories/sun-tv/', channel: 'Sun TV', code: 'sun' },
      { url: 'https://arivumani.net/categories/vijay-tv/', channel: 'Star Vijay', code: 'vijay' },
      { url: 'https://arivumani.net/categories/zee-tamil/', channel: 'Zee Tamil', code: 'zee' },
      { url: 'https://arivumani.net/', channel: 'TamilGun Feed', code: 'all' }
    ];

    const results = await Promise.allSettled(
      urls.map(u =>
        axios.get(u.url, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
          },
          timeout: 6000
        }).then(res => ({ ...u, html: res.data }))
      )
    );

    for (const r of results) {
      if (r.status === 'fulfilled' && r.value?.html) {
        const { channel, code, html } = r.value;
        const postRegex = /<article[^>]*class=["'][^"']*(?:video|post)[^"']*["'][^>]*>([\s\S]*?)<\/article>/gi;
        let m;

        while ((m = postRegex.exec(html)) !== null) {
          const postBody = m[1];
          const linkMatch = postBody.match(/<a\s+[^>]*href=["'](https?:\/\/[^"']*arivumani\.net\/[^"']+)["'][^>]*>/i);
          const titleMatch = postBody.match(/<h[1-6][^>]*class=["'][^"']*post-title[^"']*["'][^>]*>\s*<a[^>]*>([\s\S]*?)<\/a>/i);
          const imgMatch = postBody.match(/src=["'](https?:\/\/[^"']+\.(?:jpg|png|webp|jpeg))["']/i);

          if (linkMatch && titleMatch) {
            const rawTitle = titleMatch[1].replace(/<[^>]+>/g, '').trim();
            const link = linkMatch[1];
            const image = imgMatch ? imgMatch[1] : null;

            const lower = rawTitle.toLowerCase();
            const isReality = lower.includes('bigg boss') || lower.includes('super singer') || lower.includes('cooku') || lower.includes('saregamapa') || lower.includes('dance');
            const isProgramme = lower.includes('neeya naana') || lower.includes('tamizha tamizha') || lower.includes('vanakkam') || lower.includes('kondattam');
            const isEvent = lower.includes('award') || lower.includes('viruthu') || lower.includes('launch') || lower.includes('special');

            const item = {
              title: rawTitle.replace(/\s+\d{2}-\d{2}-\d{4}.*$/i, '').trim(),
              rawTitle,
              pageUrl: link,
              image,
              channel: channel === 'TamilGun Feed' ? (lower.includes('sun') ? 'Sun TV' : lower.includes('vijay') ? 'Star Vijay' : 'Zee Tamil') : channel,
              channelCode: code === 'all' ? (lower.includes('sun') ? 'sun' : lower.includes('vijay') ? 'vijay' : 'zee') : code
            };

            if (isEvent) {
              scrapedEvents.push(item);
            } else if (isProgramme || isReality) {
              scrapedShows.push(item);
            } else {
              scrapedSerials.push(item);
            }
          }
        }
      }
    }
  } catch (e) {
    console.warn('[TvSerialsLiveScraper] Scraper error:', e.message);
  }

  return {
    scrapedSerials,
    scrapedShows,
    scrapedEvents
  };
}
