/**
 * TV Serials Metadata Cache & Multi-Server Engine
 * 
 * Supports:
 * - Server 1: Tamildhool (tamildhool.tech)
 * - Server 2: Tamilgun (arivumani.net)
 * - All Serials (Sun TV, Star Vijay, Zee Tamil)
 * - Reality Shows (Bigg Boss, Super Singer, Cooku with Comali, etc.)
 * - TV Programmes (Neeya Naana, Tamizha Tamizha, Vanakkam Tamizha, etc.)
 * - Special Events & Mega Shows (Viruthugal, Audio Launches, Sunday Specials)
 */

export const SERVERS = [
  {
    id: 'tamildhool',
    name: 'Tamildhool',
    displayName: 'Server 1 (Tamildhool)',
    shortName: 'Server 1',
    domain: 'tamildhool.tech',
    protocol: 'JSON Scrape',
    cdn: 'Bunny Stream CDN',
    latency: '0ms',
    status: 'Online',
    color: '#2563eb'
  },
  {
    id: 'tamilgun',
    name: 'Tamilgun (arivumani.net)',
    displayName: 'Server 2 (Tamilgun)',
    shortName: 'Server 2',
    domain: 'arivumani.net',
    protocol: 'PlayAllu AES Decrypt',
    cdn: 'PlayAllu / Bunny CDN',
    latency: '0ms',
    status: 'Online',
    color: '#10b981'
  }
];

export const CHANNELS = [
  {
    id: 'sun',
    code: 'sun',
    name: 'Sun TV',
    tamilName: 'சன் டிவி',
    color: '#f97316',
    icon: 'sunny',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Sun_TV_logo.svg/300px-Sun_TV_logo.svg.png'
  },
  {
    id: 'vijay',
    code: 'vijay',
    name: 'Star Vijay',
    tamilName: 'விஜய் டிவி',
    color: '#ef4444',
    icon: 'star',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Star_Vijay_logo_2017.png/300px-Star_Vijay_logo_2017.png'
  },
  {
    id: 'zee',
    code: 'zee',
    name: 'Zee Tamil',
    tamilName: 'ஜீ தமிழ்',
    color: '#a855f7',
    icon: 'sparkles',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Zee_Tamil_logo.svg/300px-Zee_Tamil_logo.svg.png'
  }
];

// Rich Curated Metadata Cache for Server 1 (Tamildhool)
export const TAMILDHOOL_SERIALS_CACHE = [
  // --- SUN TV ---
  {
    id: 'td_kayal',
    serialCode: 'kayal',
    title: 'Kayal',
    tamilTitle: 'கயல்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:30 PM',
    episodesCount: '1240 episodes logged',
    episodes: '1240 Eps',
    tag: 'Daily Soap',
    networkTag: 'SUN TV • PRIME',
    networkColor: '#f97316',
    description: 'A resilient elder sister shoulders her family responsibilities, overcoming personal and financial hurdles.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_singapennae',
    serialCode: 'singapennae',
    title: 'Singapennae',
    tamilTitle: 'சிங்கப்பெண்ணே',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:00 PM',
    episodesCount: '540 episodes logged',
    episodes: '540 Eps',
    tag: 'Prime Slot',
    networkTag: 'SUN TV • PRIME',
    networkColor: '#f97316',
    description: 'Anandi leaves her rural hometown to conquer corporate challenges in the Chennai garment industry.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_vanathai_pola',
    serialCode: 'vanathai_pola',
    title: 'Vanathai Pola',
    tamilTitle: 'வானத்தை போல',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '06:30 PM',
    episodesCount: '1150 episodes logged',
    episodes: '1150 Eps',
    tag: 'Family Drama',
    networkTag: 'SUN TV • HIT',
    networkColor: '#f97316',
    description: 'An unbreakable bond of love and sacrifice between brother Chinrasu and sister Thulasi.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_marumagal',
    serialCode: 'marumagal',
    title: 'Marumagal',
    tamilTitle: 'மருமகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '07:00 PM',
    episodesCount: '380 episodes logged',
    episodes: '380 Eps',
    tag: 'Daily Soap',
    networkTag: 'SUN TV • PRIME',
    networkColor: '#f97316',
    description: 'A devoted daughter-in-law strives to bring harmony and values to her new household.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_moondru_mudichu',
    serialCode: 'moondru_mudichu',
    title: 'Moondru Mudichu',
    tamilTitle: 'மூன்று முடிச்சு',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '08:30 PM',
    episodesCount: '290 episodes logged',
    episodes: '290 Eps',
    tag: 'Daily Drama',
    networkTag: 'SUN TV • PRIME',
    networkColor: '#f97316',
    description: 'A high-voltage triangular matrimonial drama exploring fate, passion, and unexpected alliances.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_annam',
    serialCode: 'annam',
    title: 'Annam',
    tamilTitle: 'அன்னம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '01:30 PM',
    episodesCount: '310 episodes logged',
    episodes: '310 Eps',
    tag: 'Afternoon Special',
    networkTag: 'SUN TV • DRAMA',
    networkColor: '#f97316',
    description: 'A poignant tale of maternal compassion and enduring strength in village heartlands.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_lakshmi',
    serialCode: 'lakshmi',
    title: 'Lakshmi',
    tamilTitle: 'லட்சுமி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '09:00 PM',
    episodesCount: '420 episodes logged',
    episodes: '420 Eps',
    tag: 'Prime Hit',
    networkTag: 'SUN TV • PRIME',
    networkColor: '#f97316',
    description: 'Lakshmi overcomes insurmountable domestic odds with courage, truth, and dedication.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_thulasi',
    serialCode: 'thulasi',
    title: 'Thulasi',
    tamilTitle: 'துளசி',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '02:00 PM',
    episodesCount: '260 episodes logged',
    episodes: '260 Eps',
    tag: 'Daily Drama',
    networkTag: 'SUN TV • HIT',
    networkColor: '#f97316',
    description: 'A devoted village girl battles societal prejudice with truth and compassion.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },
  {
    id: 'td_iru_malargal',
    serialCode: 'iru_malargal',
    title: 'Iru Malargal',
    tamilTitle: 'இரு மலர்கள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    timeSlot: '02:30 PM',
    episodesCount: '180 episodes logged',
    episodes: '180 Eps',
    tag: 'Romantic Drama',
    networkTag: 'SUN TV • DRAMA',
    networkColor: '#f97316',
    description: 'Two intertwined souls confront destiny and deep-rooted family rivalries.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    server: 'tamildhool'
  },

  // --- STAR VIJAY ---
  {
    id: 'td_siragadikka_aasai',
    serialCode: 'siragadikka_aasai',
    title: 'Siragadikka Aasai',
    tamilTitle: 'சிறகடிக்க ஆசை',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '09:00 PM',
    episodesCount: '480 episodes logged',
    episodes: '480 Eps',
    tag: 'Top TRP',
    networkTag: 'VIJAY TV • TRENDING',
    networkColor: '#ef4444',
    description: 'An emotional roller coaster between Muthu and Meena striving for love, acceptance and dignity amidst family conflicts.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },
  {
    id: 'td_baakiyalakshmi',
    serialCode: 'baakiyalakshmi',
    title: 'Baakiyalakshmi',
    tamilTitle: 'பாக்கியலட்சுமி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '08:30 PM',
    episodesCount: '1350 episodes logged',
    episodes: '1350 Eps',
    tag: 'Prime Slot',
    networkTag: 'VIJAY TV • HIT',
    networkColor: '#ef4444',
    description: 'A devoted mother and entrepreneur journeys from a neglected homemaker to a self-made powerhouse.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },
  {
    id: 'td_pandian_stores_2',
    serialCode: 'pandian_stores_2',
    title: 'Pandian Stores 2',
    tamilTitle: 'பாண்டியன் ஸ்டோர்ஸ் 2',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '08:00 PM',
    episodesCount: '340 episodes logged',
    episodes: '340 Eps',
    tag: 'Family Saga',
    networkTag: 'VIJAY TV • PRIME',
    networkColor: '#ef4444',
    description: 'Pandian strictly guides his sons through discipline, modern entrepreneurship, and marital bonds.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },
  {
    id: 'td_mahanathi',
    serialCode: 'mahanathi',
    title: 'Mahanathi',
    tamilTitle: 'மகாநதி',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '07:00 PM',
    episodesCount: '510 episodes logged',
    episodes: '510 Eps',
    tag: 'Daily Drama',
    networkTag: 'VIJAY TV • DRAMA',
    networkColor: '#ef4444',
    description: 'Four sisters struggle to maintain unity and rebuild their shattered lives after their father dies.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },
  {
    id: 'td_aaha_kalyanam',
    serialCode: 'aaha_kalyanam',
    title: 'Aaha Kalyanam',
    tamilTitle: 'ஆஹா கல்யாணம்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '07:30 PM',
    episodesCount: '420 episodes logged',
    episodes: '420 Eps',
    tag: 'Romantic Drama',
    networkTag: 'VIJAY TV • HIT',
    networkColor: '#ef4444',
    description: 'An unconventional wedding arrangement blossoms into unexpected, heartfelt romance.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },
  {
    id: 'td_thendrale_mella_pesu',
    serialCode: 'thendrale_mella_pesu',
    title: 'Thendrale Mella Pesu',
    tamilTitle: 'தென்றலே மெல்ல பேசு',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    timeSlot: '03:00 PM',
    episodesCount: '140 episodes logged',
    episodes: '140 Eps',
    tag: 'Romantic Drama',
    networkTag: 'VIJAY TV • SPECIAL',
    networkColor: '#ef4444',
    description: 'A soft breeze of romance, family loyalties, and untold sacrifices in modern Chennai.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    server: 'tamildhool'
  },

  // --- ZEE TAMIL ---
  {
    id: 'td_karthigai_deepam',
    serialCode: 'karthigai_deepam',
    title: 'Karthigai Deepam',
    tamilTitle: 'கார்த்திகை தீபம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:00 PM',
    episodesCount: '510 episodes logged',
    episodes: '510 Eps',
    tag: 'Daily Soap',
    networkTag: 'ZEE TAMIL • PRIME',
    networkColor: '#a855f7',
    description: 'Karthik and Deepas paths cross as music, devotion, and family expectations intertwine.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  },
  {
    id: 'td_sandhya_raagam',
    serialCode: 'sandhya_raagam',
    title: 'Sandhya Raagam',
    tamilTitle: 'சந்தியா ராகம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:30 PM',
    episodesCount: '430 episodes logged',
    episodes: '430 Eps',
    tag: 'Emotional Drama',
    networkTag: 'ZEE TAMIL • HIT',
    networkColor: '#a855f7',
    description: 'Two sisters separated by circumstances reunite to navigate marriage and societal pressures.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  },
  {
    id: 'td_ayali',
    serialCode: 'ayali',
    title: 'Ayali',
    tamilTitle: 'அயலி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '06:30 PM',
    episodesCount: '160 episodes logged',
    episodes: '160 Eps',
    tag: 'Inspiring Drama',
    networkTag: 'ZEE TAMIL • SPECIAL',
    networkColor: '#a855f7',
    description: 'A bright young girl defies age-old village taboos to pursue her dream of becoming a doctor.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  },
  {
    id: 'td_thirumangalyam',
    serialCode: 'thirumangalyam',
    title: 'Thirumangalyam',
    tamilTitle: 'திருமாங்கல்யம்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '07:00 PM',
    episodesCount: '220 episodes logged',
    episodes: '220 Eps',
    tag: 'Family Drama',
    networkTag: 'ZEE TAMIL • HIT',
    networkColor: '#a855f7',
    description: 'A traditional bond of holy matrimony is tested by deceit, greed, and true love.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  },
  {
    id: 'td_samanthi',
    serialCode: 'samanthi',
    title: 'Samanthi',
    tamilTitle: 'சாமந்தி',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '08:30 PM',
    episodesCount: '190 episodes logged',
    episodes: '190 Eps',
    tag: 'Daily Drama',
    networkTag: 'ZEE TAMIL • PRIME',
    networkColor: '#a855f7',
    description: 'Samanthi confronts unexpected challenges in her marital home with wisdom and resilience.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  },
  {
    id: 'td_vaagai_sooda_vaa',
    serialCode: 'vaagai_sooda_vaa',
    title: 'Vaagai Sooda Vaa',
    tamilTitle: 'வாகை சூட வா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    timeSlot: '09:00 PM',
    episodesCount: '120 episodes logged',
    episodes: '120 Eps',
    tag: 'High TRP',
    networkTag: 'ZEE TAMIL • PRIME',
    networkColor: '#a855f7',
    description: 'An inspiring journey of justice, honor, and victory against corporate greed in modern society.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    server: 'tamildhool'
  }
];

// Rich Curated Metadata Cache for Server 2 (Tamilgun / Arivumani)
export const TAMILGUN_SERIALS_CACHE = TAMILDHOOL_SERIALS_CACHE.map(s => ({
  ...s,
  id: `tg_${s.serialCode}`,
  server: 'tamilgun',
  networkTag: `ARIVUMANI • ${s.channel.toUpperCase()}`,
  borderColor: '#10b981',
  tag: 'Server 2 Mirror'
}));

// Popular Reality Shows
export const REALITY_SHOWS_CACHE = [
  {
    id: 'reality_bigg_boss',
    serialCode: 'bigg_boss',
    title: 'Bigg Boss Tamil',
    tamilTitle: 'பிக் பாஸ் தமிழ்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: '24/7 Reality',
    timeSlot: '09:30 PM (Daily)',
    episodesCount: '105 episodes logged',
    tag: 'Mega Reality',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'Celebrities live together under 24/7 camera surveillance, facing tasks, drama, and public votes.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'reality_super_singer',
    serialCode: 'super_singer',
    title: 'Super Singer S10',
    tamilTitle: 'சூப்பர் சிங்கர் 10',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Music Talent Show',
    timeSlot: 'Sat-Sun 06:30 PM',
    episodesCount: '84 episodes logged',
    tag: 'Weekend Prime',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'The pinnacle of Tamil musical excellence where aspiring singers compete for stardom.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'reality_cooku_with_comali',
    serialCode: 'cooku_with_comali',
    title: 'Cooku with Comali S5',
    tamilTitle: 'குக் வித் கோமாளி 5',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Culinary Comedy',
    timeSlot: 'Sat-Sun 08:00 PM',
    episodesCount: '52 episodes logged',
    tag: 'Comedy Riot',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'A hilarious culinary competition pairing celebrity cooks with comic partners.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'reality_top_cooku',
    serialCode: 'top_cooku',
    title: 'Top Cooku Dupe Cooku',
    tamilTitle: 'டாப் குக் டூப் குக்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Celebrity Cooking',
    timeSlot: 'Sunday 01:30 PM',
    episodesCount: '42 episodes logged',
    tag: 'Sunday Special',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'Sun TVs riotous culinary entertainer featuring top chefs, hilarious dupe cooks, and lively banter.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'reality_saregamapa',
    serialCode: 'saregamapa',
    title: 'Sa Re Ga Ma Pa S4',
    tamilTitle: 'ச ரி க ம ப 4',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Vocal Showdown',
    timeSlot: 'Sat-Sun 07:00 PM',
    episodesCount: '60 episodes logged',
    tag: 'Musical Gala',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    description: 'Zee Tamils premier vocal talent hunt celebrating legendary melodies and extraordinary singers.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 'reality_dance_jodi_dance',
    serialCode: 'dance_jodi_dance',
    title: 'Dance Jodi Dance',
    tamilTitle: 'டான்ஸ் ஜோடி டான்ஸ்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Choreography Contest',
    timeSlot: 'Sat-Sun 08:30 PM',
    episodesCount: '48 episodes logged',
    tag: 'Dance Battle',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    description: 'Dynamic dance couples ignite the stage with mind-blowing choreography and acrobatic skill.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  },
  {
    id: 'reality_start_music',
    serialCode: 'start_music',
    title: 'Start Music',
    tamilTitle: 'ஸ்டார்ட் மியூசிக்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Game Show',
    timeSlot: 'Sunday 08:00 PM',
    episodesCount: '65 episodes logged',
    tag: 'Fun Game',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'TV stars battle in musical buzzer games and funny vault challenges with high energy.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4'
  }
];

// TV Programmes & Talk Shows Category
export const TV_PROGRAMMES_CACHE = [
  {
    id: 'prg_neeya_naana',
    serialCode: 'neeya_naana',
    title: 'Neeya Naana',
    tamilTitle: 'நீயா நானா',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Talk Show',
    timeSlot: 'Sunday 12:30 PM',
    episodesCount: '820 episodes logged',
    tag: 'Debate Show',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'Iconic talk show hosted by Gopinath debating intense societal viewpoints and contemporary culture.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'
  },
  {
    id: 'prg_tamizha_tamizha',
    serialCode: 'tamizha_tamizha',
    title: 'Tamizha Tamizha',
    tamilTitle: 'தமிழா தமிழா',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Talk Show',
    timeSlot: 'Sunday 12:00 PM',
    episodesCount: '340 episodes logged',
    tag: 'Debate Show',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    description: 'A hard-hitting opinion forum bringing real people together to voice pressing cultural and social themes.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'
  },
  {
    id: 'prg_vanakkam_tamizha',
    serialCode: 'vanakkam_tamizha',
    title: 'Vanakkam Tamizha',
    tamilTitle: 'வணக்கம் தமிழா',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Morning Show',
    timeSlot: 'Daily 08:00 AM',
    episodesCount: '1950 episodes logged',
    tag: 'Celebrity Talk',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'Sun TVs flagship morning magazine featuring celebrity interviews, astrology, and inspiring stories.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4'
  },
  {
    id: 'prg_sunday_kondattam',
    serialCode: 'sunday_kondattam',
    title: 'Sunday Kondattam',
    tamilTitle: 'சண்டே கொண்டாட்டம்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Game Show',
    timeSlot: 'Sunday 09:30 AM',
    episodesCount: '210 episodes logged',
    tag: 'Entertainment',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'A vibrant weekend celebration of music, comedy sketches, celebrity banter, and family games.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'
  },
  {
    id: 'prg_cine_mini',
    serialCode: 'cine_mini',
    title: 'Cine Mini',
    tamilTitle: 'சினி மினி',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Cinema & Buzz',
    timeSlot: 'Saturday 11:00 AM',
    episodesCount: '480 episodes logged',
    tag: 'Kollywood',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'Exclusive behind-the-scenes glimpses, interviews, and reviews from the heart of Kollywood.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4'
  }
];

// Special Events & Mega Shows Category
export const SPECIAL_EVENTS_CACHE = [
  {
    id: 'event_vijay_awards',
    serialCode: 'vijay_awards',
    title: 'Vijay Television Awards',
    tamilTitle: 'விஜய் தொலைக்காட்சி விருதுகள்',
    channel: 'Star Vijay',
    channelCode: 'vijay',
    genre: 'Grand Gala',
    timeSlot: 'Annual Mega Event',
    episodesCount: 'Annual Special',
    tag: 'Mega Event',
    bgColor: '#1e1b4b',
    tamilColor: '#818cf8',
    borderColor: '#818cf8',
    description: 'The star-studded red carpet celebration honoring the finest actors, directors, and technicians of Vijay TV.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4'
  },
  {
    id: 'event_sun_viruthugal',
    serialCode: 'sun_viruthugal',
    title: 'Sun Kudumba Viruthugal',
    tamilTitle: 'சன் குடும்ப விருதுகள்',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Star Honors Ceremony',
    timeSlot: 'Prime Mega Event',
    episodesCount: 'Annual Special',
    tag: 'Award Ceremony',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'Sun Networks most prestigious awards night celebrating beloved TV families, actors, and serial directors.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 'event_zee_viruthugal',
    serialCode: 'zee_viruthugal',
    title: 'Zee Kudumba Viruthugal',
    tamilTitle: 'ஜீ குடும்ப விருதுகள்',
    channel: 'Zee Tamil',
    channelCode: 'zee',
    genre: 'Grand Celebration',
    timeSlot: 'Annual Gala Night',
    episodesCount: 'Annual Special',
    tag: 'Award Night',
    bgColor: '#2a122e',
    tamilColor: '#c084fc',
    borderColor: '#c084fc',
    description: 'A dazzling extravaganza of performances, emotional reunions, and awards for Zee Tamils star artists.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 'event_audio_launch',
    serialCode: 'audio_launch',
    title: 'Kollywood Audio Launches',
    tamilTitle: 'திரைப்பட இசை வெளியீட்டு விழா',
    channel: 'Sun TV',
    channelCode: 'sun',
    genre: 'Exclusive Cinema Event',
    timeSlot: 'Weekend Special',
    episodesCount: 'Weekend Mega Event',
    tag: 'Cinema Special',
    bgColor: '#172033',
    tamilColor: '#38bdf8',
    borderColor: '#38bdf8',
    description: 'Grand movie audio release events, celebrity speeches, and live musical concerts from leading Kollywood stars.',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  }
];

export function getCachedSerialsForServer(serverId = 'tamildhool') {
  if (serverId === 'tamilgun') {
    return TAMILGUN_SERIALS_CACHE;
  }
  return TAMILDHOOL_SERIALS_CACHE;
}

export function findSerial(serialIdOrCode, serverId = 'tamildhool') {
  const list = getCachedSerialsForServer(serverId);
  const found = list.find(s => s.id === serialIdOrCode || s.serialCode === serialIdOrCode);
  if (found) return found;
  const inReality = REALITY_SHOWS_CACHE.find(r => r.id === serialIdOrCode || r.serialCode === serialIdOrCode);
  if (inReality) return inReality;
  const inPrg = TV_PROGRAMMES_CACHE.find(p => p.id === serialIdOrCode || p.serialCode === serialIdOrCode);
  if (inPrg) return inPrg;
  const inEvent = SPECIAL_EVENTS_CACHE.find(e => e.id === serialIdOrCode || e.serialCode === serialIdOrCode);
  return inEvent || list[0];
}
